# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'image.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\x05image\"\x1e\n\x0cImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"^\n\rImageResponse\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x13\n\x0bprompt_hash\x18\x02 \x01(\t\x12\x11\n\tfile_type\x18\x03 \x01(\t\x12\x11\n\timage_url\x18\x04 \x01(\t\"\x1f\n\x0c\x42\x61tchRequest\x12\x0f\n\x07prompts\x18\x01 \x03(\t\"f\n\tBatchItem\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x13\n\x0bprompt_hash\x18\x02 \x01(\t\x12\x12\n\nimage_data\x18\x03 \x01(\x0c\x12\x11\n\tfile_type\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t\"0\n\rBatchResponse\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.image.BatchItem2\x86\x01\n\x0cImageService\x12:\n\rGenerateImage\x12\x13.image.ImageRequest\x1a\x14.image.ImageResponse\x12:\n\rGenerateBatch\x12\x13.image.BatchRequest\x1a\x14.image.BatchResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_IMAGEREQUEST']._serialized_start=22
  _globals['_IMAGEREQUEST']._serialized_end=52
  _globals['_IMAGERESPONSE']._serialized_start=54
  _globals['_IMAGERESPONSE']._serialized_end=148
  _globals['_BATCHREQUEST']._serialized_start=150
  _globals['_BATCHREQUEST']._serialized_end=181
  _globals['_BATCHITEM']._serialized_start=183
  _globals['_BATCHITEM']._serialized_end=285
  _globals['_BATCHRESPONSE']._serialized_start=287
  _globals['_BATCHRESPONSE']._serialized_end=335
  _globals['_IMAGESERVICE']._serialized_start=338
  _globals['_IMAGESERVICE']._serialized_end=472
# @@protoc_insertion_point(module_scope)
